[project]
name = "prompt-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-openai>=0.3.12",
    "langgraph>=0.3.29",
    "pydantic-settings>=2.8.1",
]
